name: udhaarkaroapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^3.2.0+1
  material_design_icons_flutter: ^4.0.5855
  qr_code_scanner: ^0.4.0
  fluttertoast: ^7.1.8
  flutter_launcher_icons: "^0.9.2"
  page_transition: ^1.1.7+6
  flutter_spinkit: "^4.1.2"
  sweetalert: ^0.0.1
  curved_navigation_bar: ^0.3.7
  flare_flutter: ^2.0.6
  intl: ^0.17.0
  sizer: ^1.1.8
  image_picker: ^0.8.4+4
  get: ^3.26.0
  http: ^0.13.0
  flutter_otp_text_field: ^0.0.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  qr_flutter: ^4.0.0
  circular_reveal_animation: ^2.0.0
  firebase_messaging: ^10.0.7
  flutter_local_notifications: ^8.1.1+1
  encrypt: ^5.0.0
  #google_mobile_ads: ^1.0.0
  pull_to_refresh: ^2.0.0
  badges: ^1.2.0
  flutter_contacts: ^1.1.0+3
  package_info: ^2.0.2
  store_redirect: ^2.0.0
  flutter_dotenv: ^5.0.2
  webview_flutter: ^2.1.1
  lint: ^1.7.2
  share_plus: ^2.1.4
  shared_preferences: ^2.0.8
  translator: ^0.1.7
  flutter_slidable: ^0.6.0
  wakelock: ^0.5.6
  url_launcher: ^6.0.12
  intro_slider: ^3.0.2
  round_spot: ^0.5.0
  path_provider: ^2.0.5
  is_first_run: ^1.0.0
  image_cropper: ^1.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  slider_button: ^0.6.0
  flutter_native_splash: 1.2.4

flutter_native_splash:
  image: assets/images/splash.png
  background_image: assets/images/splashbg.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/flares/
    - .env

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
